# Generated by Django 4.0.2 on 2022-04-26 19:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=24)),
                ('lastName', models.CharField(max_length=24)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=24)),
                ('profession', models.CharField(max_length=24)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
