# Generated by Django 4.0.2 on 2022-04-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationApp', '0002_person_createddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='haveWork',
            field=models.BooleanField(default=False),
        ),
    ]
